[package]
name = "rust-kenburns"
version = "0.1.0"
authors = ["Astro <astro@spaceboyz.net>"]

[dependencies]
glium = "0.18.1"
image = "*"
time = "*"
futures = "*"
tokio-core = "*"
hyper = "0.11.7"
hyper-tls = "*"
treexml = "*"
num-iter = "*"
